name        : libgusb
version     : 0.2.7
release     : 4
source     :
    - http://people.freedesktop.org/~hughsient/releases/libgusb-0.2.7.tar.xz : 0be9578f7875cecb6c163ad47eb39bc6bf497e501b08986c0d384748a054c3ee
license     :
    - LGPL-2.1
summary     : GObject wrapper for libusb
builddeps   :
    - pkgconfig(libusb-1.0)
description : |
    The libgusb package contains the GObject wrappers for libusb-1.0 that makes it easy to do asynchronous control, bulk and interrupt transfers with proper cancellation and integration into a mainloop.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
