name       : libgusb
version    : 0.4.2
release    : 13
source     :
    - https://github.com/hughsie/libgusb/archive/refs/tags/0.4.2.tar.gz : 01a99aec431cc5e80979f8aad11e0e8f1aac3fd8504d3c2f2f2c0956bc35837b
license    : LGPL-2.1-or-later
component  : system.base
summary    : GObject wrapper for libusb
description: |
    The libgusb package contains the GObject wrappers for libusb-1.0 that makes it easy to do asynchronous control, bulk and interrupt transfers with proper cancellation and integration into a mainloop.
emul32     : yes
builddeps  :
    - pkgconfig32(gio-unix-2.0)
    - pkgconfig32(json-glib-1.0)
    - pkgconfig32(libusb-1.0)
    - pkgconfig32(mount)
    - gi-docgen
    - vala
patterns   :
    - docs :
        - /usr/share/doc/*
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        normOpts="-Dintrospection=false -Dvapi=false"
    else
        normOpts="-Dintrospection=true -Dvapi=true"
    fi
    %meson_configure $normOpts
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
