name       : libgusb
version    : 0.3.4
release    : 12
source     :
    - https://github.com/hughsie/libgusb/archive/0.3.4.tar.gz : 07049389eb20847eedb664e2a2d954412a28bee125647ea6a445c59bebbd9944
license    : LGPL-2.1-or-later
summary    : GObject wrapper for libusb
component  : system.base
builddeps  :
    - pkgconfig32(gio-unix-2.0)
    - pkgconfig32(libusb-1.0)
    - pkgconfig32(mount)
    - pkgconfig(gtk-doc)
    - vala
emul32     : yes
description: |
    The libgusb package contains the GObject wrappers for libusb-1.0 that makes it easy to do asynchronous control, bulk and interrupt transfers with proper cancellation and integration into a mainloop.
setup      : |
    %meson_configure --prefix=/usr
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
