name       : libgusb
version    : 0.2.10
release    : 7
source     :
    - https://people.freedesktop.org/~hughsient/releases/libgusb-0.2.10.tar.xz : 5c0442f5e00792bea939bbd16df09245740ae0d8b6ad9890d09189e1f4a3a17a
license    :
    - LGPL-2.1
summary    : GObject wrapper for libusb
component  : system.base
builddeps  :
    - pkgconfig32(libusb-1.0)
    - pkgconfig32(gio-unix-2.0)
emul32     : yes
description: |
    The libgusb package contains the GObject wrappers for libusb-1.0 that makes it easy to do asynchronous control, bulk and interrupt transfers with proper cancellation and integration into a mainloop.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
