name       : libgusb
version    : 0.3.0
release    : 11
source     :
    - https://github.com/hughsie/libgusb/archive/0.3.0.tar.gz : b36310f8405d5fd68f6caf4a829f7ab4c627b38fd3d02a139d411fce0f3a49f1
license    : LGPL-2.1
summary    : GObject wrapper for libusb
component  : system.base
builddeps  :
    - pkgconfig32(gio-unix-2.0)
    - pkgconfig32(libusb-1.0)
    - pkgconfig32(mount)
    - pkgconfig(gtk-doc)
    - vala
emul32     : yes
description: |
    The libgusb package contains the GObject wrappers for libusb-1.0 that makes it easy to do asynchronous control, bulk and interrupt transfers with proper cancellation and integration into a mainloop.
setup      : |
    %meson_configure --prefix=/usr
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
